### ISSUE TITLE
Add a txt version of Doom Emacs Handbook PDF

### ISSUE THREAD

**Issue by rhiroyuki** [otavioschwanck/doom_emacs_dotfiles#3]
First of all, thank you for creating this repo, I just started using emacs and found out this amazing repo.

I was wondering if we could get a txt/md version of [Doom Emacs Handbook](https://github.com/otavioschwanck/doom-emacs-on-rails/blob/master/Emacs%20Handbook.pdf). It would be much easier for me to read it and get used to the shortcuts.

I can make a draft PR with a txt version if that's ok.

Thank you!

**Comment by otavioschwanck** [comment]
Nice idea, ill make an org version of that!

**Comment by otavioschwanck** [comment]
Hi @rhiroyuki 

Release the text version of the handbook.  Please upgrade your emacs with M-x upgrade-doom-emacs-on-rails.

To access the handbook inside emacs, you can press `SPC f h`.

The file version: https://github.com/otavioschwanck/doom-emacs-on-rails/blob/master/emacs-handbook.org

If the upgrade runs smoothly, you will see this startup on your emacs:

![image](https://user-images.githubusercontent.com/9551316/151469418-0eba8e1b-4f00-43aa-a82b-c7d84b405853.png)

PS:  English is not my native language, so, if you run into a typo, please notify me or send a PR.  Thanks for your idea!

If everything is ok, please, close this issue!

EDIT:

Po Ricardo, sou BR também, hahah

**Comment by rhiroyuki** [comment]
Thank you! Works wonderfully :rocket: 

![image](https://user-images.githubusercontent.com/4009367/151607302-799039c7-756f-47f8-91f4-d41c5a46434d.png)

Valeu @otavioschwanck sou BR :brazil:  sim hahaha
Obrigado por esse handbook, ajuda muito principalmente para iniciantes em emacs como eu :pray:
