### ISSUE TITLE
Ruby-ls error on start

### ISSUE THREAD

**Issue by javid-g** [otavioschwanck/doom_emacs_dotfiles#6]
I'll preface this by saying i am completely new to all of emacs/doom emacs and doom emacs on rails 🙂 

When I launch a ruby file within a rails project I get this error:
![Screenshot 2023-02-04 at 7 29 04 PM](https://user-images.githubusercontent.com/92900940/216798432-f5c1c018-e708-4eda-bc21-f331c72f9a11.png)

Any ideas on this?

**Comment by otavioschwanck** [comment]
> I'll preface this by saying i am completely new to all of emacs/doom emacs and doom emacs on rails 🙂
> 
> When I launch a ruby file within a rails project I get this error: ![Screenshot 2023-02-04 at 7 29 04 PM](https://user-images.githubusercontent.com/92900940/216798432-f5c1c018-e708-4eda-bc21-f331c72f9a11.png)
> 
> Any ideas on this?

Make sure to use rbenv.

Install the solargraph gem:

gem install solargraph (using the version of your project)

**Comment by javid-g** [comment]
Ah, of course! Thank you for the quick response.
